# Generated by Django 3.1.6 on 2021-06-04 16:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=65, verbose_name='Nombre del cliente')),
                ('apellido', models.CharField(max_length=65, verbose_name='Apellido del cliente')),
                ('cedula', models.IntegerField()),
                ('num_telf', models.BigIntegerField()),
                ('email', models.EmailField(max_length=254, verbose_name='Correo Electronico')),
                ('direccion', models.CharField(max_length=500, verbose_name='Direccion del cliente')),
            ],
            options={
                'verbose_name_plural': 'Clientes',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='Estado',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('etapa', models.CharField(max_length=65, verbose_name='Etapa del proceso')),
            ],
            options={
                'verbose_name_plural': 'Etapa del pedido',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='Partes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_parte', models.CharField(max_length=65, verbose_name='Tipo de parte')),
                ('serial_parte', models.CharField(max_length=65, verbose_name='Serial de las parte')),
            ],
        ),
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orden_pedido', models.BigIntegerField()),
                ('fecha_ingreso', models.DateField()),
                ('fecha_taller', models.DateField(blank=True)),
                ('fecha_egreso', models.DateField(blank=True)),
                ('qr_code', models.ImageField(blank=True, upload_to='qr_codes')),
                ('estado', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='servicio.estado')),
                ('partes', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='servicio.partes')),
                ('persona', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='servicio.cliente')),
            ],
            options={
                'verbose_name_plural': 'Pedidos',
                'ordering': ['-id'],
            },
        ),
    ]
