# Generated by Django 3.1 on 2021-07-13 20:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=65, verbose_name='Nombre del cliente')),
                ('apellido', models.CharField(max_length=65, verbose_name='Apellido del cliente')),
                ('cedula', models.IntegerField()),
                ('num_telf', models.BigIntegerField()),
                ('email', models.EmailField(max_length=254, verbose_name='Correo Electronico')),
                ('direccion', models.TextField(max_length=500, verbose_name='Direccion del cliente')),
            ],
            options={
                'verbose_name_plural': 'Clientes',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='Partes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_parte', models.CharField(max_length=65, verbose_name='Tipo de parte')),
                ('serial_parte', models.CharField(max_length=20, verbose_name='Serial de las parte')),
                ('if_garantia', models.BooleanField(null=True)),
                ('observacion', models.CharField(max_length=250, verbose_name='Observacion de la parte')),
                ('emplo_name', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Partes por arreglar',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orden_pedido', models.BigIntegerField()),
                ('fecha_ingreso', models.DateField()),
                ('fecha_taller', models.DateField(blank=True, null=True)),
                ('fecha_egreso', models.DateField(blank=True, null=True)),
                ('qr_code', models.ImageField(blank=True, upload_to='qr_codes')),
                ('partes', models.ManyToManyField(to='servicio.Partes')),
                ('persona', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='servicio.cliente')),
            ],
            options={
                'verbose_name_plural': 'Pedidos',
                'ordering': ['-id'],
            },
        ),
    ]
