# Generated by Django 3.1.6 on 2021-05-28 14:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('servicio', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pedido',
            old_name='fehc_egreso',
            new_name='fecha_egreso',
        ),
    ]
