# Generated by Django 3.1 on 2021-07-13 21:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('servicio', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pedido',
            name='qr_code',
        ),
    ]
