# Generated by Django 3.1.6 on 2021-06-04 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicio', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pedido',
            name='partes',
        ),
        migrations.AddField(
            model_name='pedido',
            name='partes',
            field=models.ManyToManyField(to='servicio.Partes'),
        ),
    ]
