# Generated by Django 3.1.6 on 2021-05-28 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicio', '0002_auto_20210528_1424'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='fecha_egreso',
            field=models.DateField(blank=True),
        ),
    ]
