# Generated by Django 3.1.6 on 2021-06-04 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicio', '0002_auto_20210604_1613'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='fecha_taller',
            field=models.DateField(blank=True, null=True),
        ),
    ]
