# Generated by Django 3.1.6 on 2021-06-04 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicio', '0003_auto_20210604_1617'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='fecha_egreso',
            field=models.DateField(blank=True, null=True),
        ),
    ]
