# Generated by Django 3.1.6 on 2021-05-28 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicio', '0003_auto_20210528_1424'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pedido',
            name='estado',
        ),
        migrations.AddField(
            model_name='pedido',
            name='estado',
            field=models.ManyToManyField(blank=True, null=True, to='servicio.Estado'),
        ),
    ]
