# Generated by Django 3.1.6 on 2021-06-10 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicio', '0004_auto_20210604_1618'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='direccion',
            field=models.TextField(max_length=500, verbose_name='Direccion del cliente'),
        ),
    ]
