# Generated by Django 3.1.6 on 2021-05-28 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicio', '0004_auto_20210528_1847'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='estado',
            field=models.ManyToManyField(to='servicio.Estado'),
        ),
    ]
