# Generated by Django 3.1.6 on 2021-06-11 14:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('servicio', '0005_auto_20210610_1306'),
    ]

    operations = [
        migrations.CreateModel(
            name='ParteProceso',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('proceso', models.CharField(max_length=65, verbose_name='Proceso de la parte')),
            ],
            options={
                'verbose_name_plural': 'Proceso de la parte',
                'ordering': ['-id'],
            },
        ),
        migrations.AddField(
            model_name='partes',
            name='proceso',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='servicio.parteproceso'),
        ),
    ]
