# Generated by Django 3.1.6 on 2021-05-28 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicio', '0006_auto_20210528_1859'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='tracking',
            field=models.BigIntegerField(blank=True),
        ),
    ]
