# Generated by Django 3.1.6 on 2021-07-07 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicio', '0010_auto_20210612_1536'),
    ]

    operations = [
        migrations.AddField(
            model_name='partes',
            name='if_garantia',
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name='partes',
            name='serial_parte',
            field=models.CharField(max_length=20, verbose_name='Serial de las parte'),
        ),
    ]
