# Generated by Django 3.1.6 on 2021-05-29 20:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_auto_20210521_1817'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Empleado',
        ),
    ]
